services:
  emqx:
    image: emqx/emqx:latest
    container_name: iot_broker_emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    environment:
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=emqxpassword
      - EMQX_AUTH__USER__1__USERNAME=mqttuser
      - EMQX_AUTH__USER__1__PASSWORD=mqttpassword
    networks:
      - iot-net
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: iot_database_influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword  # Changed from "admin" to "adminpassword" (12 characters)
      - DOCKER_INFLUXDB_INIT_ORG=my_iot_org
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my_super_secret_token
    networks:
      - iot-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  telegraf:
    image: telegraf:1.30.0
    container_name: iot_agent_telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      emqx:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    networks:
      - iot-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: iot_dashboard_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafanapassword
      - GF_SECURITY_ADMIN_EMAIL=admin@localhost
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - iot-net
    restart: unless-stopped

#  # --- The simulator service is now commented out ---
#  simulator:
#    build: .
#    container_name: iot_simulator_python
#    depends_on:
#      emqx:
#        condition: service_healthy
#    networks:
#      - iot-net
#    restart: unless-stopped

networks:
  iot-net:
    driver: bridge

volumes:
  emqx_data:
  influxdb_data:
  grafana_data:
